.TH "include/TTT Directory Reference" 3 "Tue Mar 7 2023" "Version v1.0.1" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/TTT Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTTT\&.hpp\fP"
.br
.RI "This is the header file and where everything is declared\&. "
.in -1c
