.TH "src Directory Reference" 3 "Tue Mar 7 2023" "Version v1.0.0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTTT_Log\&.cpp\fP"
.br
.RI "Defines the 'Log' class\&. "
.ti -1c
.RI "file \fBTTT_Utils\&.cpp\fP"
.br
.RI "Defines the 'Utils' class\&. "
.ti -1c
.RI "file \fBTTT_Window\&.cpp\fP"
.br
.RI "Defines the 'Window' class\&. "
.in -1c
