.TH "submodules/doxygen-awesome-css Directory Reference" 3 "Mon Mar 6 2023" "Version 0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
submodules/doxygen-awesome-css Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdocs\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.in -1c
