.TH "submodules/doxygen-awesome-css/include/MyLibrary/example.hpp" 3 "Mon Mar 6 2023" "Version 0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
submodules/doxygen-awesome-css/include/MyLibrary/example.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::Example\fP"
.br
.RI "Example class to demonstrate the features of the custom CSS\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMyLibrary\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMyLibrary::Color\fP { \fBMyLibrary::red\fP, \fBMyLibrary::green\fP, \fBMyLibrary::blue\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
