.TH "md_CHANGELOG" 3 "Thu Mar 9 2023" "Version v1.0.1" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CHANGELOG \- CHANGELOG 
.PP

.SH "Release Notes"
.PP
These are the release notes for each new version of TTT\&.
.SS "v1\&.0\&.1 | Mar\&. 7, 2023"
\fBAdded\fP
.IP "\(bu" 2
New static variable \fCdefaultEventLoopFontFilename\fP
.PP
.SS "v1\&.0\&.0 | Mar\&. 5, 2023"
.IP "\(bu" 2
Initial release 
.PP

