.TH "submodules/doxygen-awesome-css/include/MyLibrary/subclass-example.hpp" 3 "Mon Mar 6 2023" "Version 0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
submodules/doxygen-awesome-css/include/MyLibrary/subclass-example.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'example\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::SubclassExample< TemplatedClass >\fP"
.br
.RI "some subclass "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMyLibrary\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
