.TH "include/TTT/TTT.hpp" 3 "Mon Mar 6 2023" "Version v1.0.0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/TTT/TTT.hpp \- This is the header file and where everything is declared\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <SFML/Window\&.hpp>\fP
.br
\fC#include <SFML/System\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTTT::Window\fP"
.br
.RI "The 'Window' class initializes the window and everything else (like the default event loop)\&. "
.ti -1c
.RI "class \fBTTT::Utils\fP"
.br
.RI "Utilities class for smaller and miscellaneous functions like the 'showFPS' one\&. "
.ti -1c
.RI "class \fBTTT::Log\fP"
.br
.RI "Logger class not really meant to be used outside of the library\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTTT\fP"
.br
.RI "The TTT namespace, which includes everything in the library\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::string \fBTTT::module\fP"
.br
.RI "Type definition for different modules\&. "
.ti -1c
.RI "typedef std::string \fBTTT::level\fP"
.br
.RI "Type definition for different levels\&. "
.ti -1c
.RI "typedef std::string \fBTTT::color\fP"
.br
.RI "Type definition for different colors\&. "
.in -1c
.SH "Detailed Description"
.PP 
This is the header file and where everything is declared\&. 


.PP
Definition in file \fBTTT\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
