.TH "TTT::Log" 3 "Mon Mar 6 2023" "Version v1.0.0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTT::Log \- Logger class not really meant to be used outside of the library\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'TTT\&.hpp'\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBlog\fP (\fBmodule\fP \fBmodule\fP, \fBlevel\fP \fBlevel\fP, std::string message)"
.br
.RI "Function to log the debug output to the terminal and/or the 'TTT\&.log' file\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBmodule\fP \fBTTT\fP = 'TTT'"
.br
.RI "Module used in the most critical of logs\&. "
.ti -1c
.RI "static const \fBmodule\fP \fBWINDOW\fP = 'WINDOW'"
.br
.RI "Module used in logging everything that has to do with the window\&. "
.ti -1c
.RI "static const \fBmodule\fP \fBUTILS\fP = 'UTILS'"
.br
.RI "Module used in logging everything that has to do with the utilities class\&. "
.ti -1c
.RI "static const \fBmodule\fP \fBLOG\fP = 'LOG'"
.br
.RI "Module used in logging everything that has to do with the logger class\&. "
.ti -1c
.RI "static const \fBmodule\fP \fBSFML\fP = 'SFML'"
.br
.RI "Module used in logging everything that has to do with the SFML library\&. "
.ti -1c
.RI "static const \fBlevel\fP \fBSUCCESS\fP = 'SUCCESS'"
.br
.RI "Success level indicates that an operation was successful\&. "
.ti -1c
.RI "static const \fBlevel\fP \fBINFO\fP = 'INFO'"
.br
.RI "Info level displays basic information\&. "
.ti -1c
.RI "static const \fBlevel\fP \fBWARNING\fP = 'WARNING'"
.br
.RI "Warning level indicates that there's something wrong with the program but doesn't require immediate attention\&. "
.ti -1c
.RI "static const \fBlevel\fP \fBERROR\fP = 'ERROR'"
.br
.RI "Error level indicates that there's something wrong with the program requires attention\&. "
.ti -1c
.RI "static const \fBlevel\fP \fBCRITICAL\fP = 'CRITICAL'"
.br
.RI "Critical level indicates that there's something wrong with the program and requires immediate attention\&. "
.ti -1c
.RI "static const \fBcolor\fP \fBRESET\fP = '\\033[0m'"
.br
.RI "Reset color resets all of the colors to the terminal default\&. "
.ti -1c
.RI "static const \fBcolor\fP \fBRED\fP = '\\033[31m'"
.br
.RI "Red color paints output red\&. Used in critical errors\&. "
.ti -1c
.RI "static const \fBcolor\fP \fBGREEN\fP = '\\033[32m'"
.br
.RI "Green color paints output green\&. Used when something is successful\&. "
.ti -1c
.RI "static const \fBcolor\fP \fBWHITE\fP = '\\033[37m'"
.br
.RI "White color paints output white\&. Used when displaying basic information\&. "
.ti -1c
.RI "static const \fBcolor\fP \fBL_RED\fP = '\\033[91m'"
.br
.RI "Light red color paints output light red\&. Used in errors\&. "
.ti -1c
.RI "static const \fBcolor\fP \fBL_YELLOW\fP = '\\033[93m'"
.br
.RI "Light yellow color paints output light yellow\&. used in warnings\&. "
.in -1c
.SH "Detailed Description"
.PP 
Logger class not really meant to be used outside of the library\&. 
.PP
Definition at line \fB52\fP of file \fBTTT\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TTT::Log::log (\fBmodule\fP module, \fBlevel\fP level, std::string message)\fC [static]\fP"

.PP
Function to log the debug output to the terminal and/or the 'TTT\&.log' file\&. 
.PP
\fBParameters\fP
.RS 4
\fImodule\fP module representing the file or library the info/error/success was noted in\&. 
.br
\fIlevel\fP level representing the level of severity that was logged\&. 
.br
\fImessage\fP a string representing the message associated with the log\&. 
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBTTT_Log\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBlevel\fP TTT::Log::CRITICAL = 'CRITICAL'\fC [static]\fP"

.PP
Critical level indicates that there's something wrong with the program and requires immediate attention\&. 
.PP
Definition at line \fB68\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBlevel\fP TTT::Log::ERROR = 'ERROR'\fC [static]\fP"

.PP
Error level indicates that there's something wrong with the program requires attention\&. 
.PP
Definition at line \fB67\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBcolor\fP TTT::Log::GREEN = '\\033[32m'\fC [static]\fP"

.PP
Green color paints output green\&. Used when something is successful\&. 
.PP
Definition at line \fB72\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBlevel\fP TTT::Log::INFO = 'INFO'\fC [static]\fP"

.PP
Info level displays basic information\&. 
.PP
Definition at line \fB65\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBcolor\fP TTT::Log::L_RED = '\\033[91m'\fC [static]\fP"

.PP
Light red color paints output light red\&. Used in errors\&. 
.PP
Definition at line \fB74\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBcolor\fP TTT::Log::L_YELLOW = '\\033[93m'\fC [static]\fP"

.PP
Light yellow color paints output light yellow\&. used in warnings\&. 
.PP
Definition at line \fB75\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBmodule\fP TTT::Log::LOG = 'LOG'\fC [static]\fP"

.PP
Module used in logging everything that has to do with the logger class\&. 
.PP
Definition at line \fB61\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBcolor\fP TTT::Log::RED = '\\033[31m'\fC [static]\fP"

.PP
Red color paints output red\&. Used in critical errors\&. 
.PP
Definition at line \fB71\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBcolor\fP TTT::Log::RESET = '\\033[0m'\fC [static]\fP"

.PP
Reset color resets all of the colors to the terminal default\&. 
.PP
Definition at line \fB70\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBmodule\fP TTT::Log::SFML = 'SFML'\fC [static]\fP"

.PP
Module used in logging everything that has to do with the SFML library\&. 
.PP
Definition at line \fB62\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBlevel\fP TTT::Log::SUCCESS = 'SUCCESS'\fC [static]\fP"

.PP
Success level indicates that an operation was successful\&. 
.PP
Definition at line \fB64\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBmodule\fP TTT::Log::TTT = 'TTT'\fC [static]\fP"

.PP
Module used in the most critical of logs\&. 
.PP
Definition at line \fB57\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBmodule\fP TTT::Log::UTILS = 'UTILS'\fC [static]\fP"

.PP
Module used in logging everything that has to do with the utilities class\&. 
.PP
Definition at line \fB60\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBlevel\fP TTT::Log::WARNING = 'WARNING'\fC [static]\fP"

.PP
Warning level indicates that there's something wrong with the program but doesn't require immediate attention\&. 
.PP
Definition at line \fB66\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBcolor\fP TTT::Log::WHITE = '\\033[37m'\fC [static]\fP"

.PP
White color paints output white\&. Used when displaying basic information\&. 
.PP
Definition at line \fB73\fP of file \fBTTT\&.hpp\fP\&.
.SS "const \fBmodule\fP TTT::Log::WINDOW = 'WINDOW'\fC [static]\fP"

.PP
Module used in logging everything that has to do with the window\&. 
.PP
Definition at line \fB59\fP of file \fBTTT\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
