.TH "src/TTT_Log.cpp" 3 "Mon Mar 6 2023" "Version v1.0.0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TTT_Log.cpp \- Defines the 'Log' class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'include/TTT/TTT\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTTT\fP"
.br
.RI "The TTT namespace, which includes everything in the library\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBTTT::currentTime\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::fstream \fBTTT::logFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the 'Log' class\&. 


.PP
Definition in file \fBTTT_Log\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
