.TH "src/TTT_Window.cpp" 3 "Thu Mar 9 2023" "Version v1.0.1" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TTT_Window.cpp \- Defines the 'Window' class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'include/TTT/TTT\&.hpp'\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTTT\fP"
.br
.RI "The TTT namespace, which includes everything in the library\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the 'Window' class\&. 


.PP
Definition in file \fBTTT_Window\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
