.TH "TTT::Utils" 3 "Thu Mar 9 2023" "Version v1.0.1" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTT::Utils \- Utilities class for smaller and miscellaneous functions like the 'showFPS' one\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'TTT\&.hpp'\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBshowFPS\fP (sf::RenderWindow &window, const sf::Font &font, unsigned int fontSize, sf::Color \fBcolor\fP=sf::Color::White)"
.br
.RI "'showFPS' calculates and displays a nice FPS number when the 'F3' key is pressed\&. "
.ti -1c
.RI "static sf::Font \fBcreateFont\fP (std::string filename)"
.br
.RI "Function to create a font and load it\&. Shortens the amount of code that has to be written\&. "
.ti -1c
.RI "static sf::Sprite \fBcreateSprite\fP (sf::Texture &texture, std::string filename)"
.br
.RI "Function to create and load a texture to a sprite\&. Shortens the amount of code that has to be written\&. "
.ti -1c
.RI "static void \fBsleepFor\fP (int timeInSeconds)"
.br
.RI "Function makes the program 'sleep' for a specified amount of time in seconds\&. "
.ti -1c
.RI "static sf::Text \fBcreateText\fP (const sf::Font &font, unsigned int fontSize, sf::Vector2f position, std::string textContents)"
.br
.RI "Function creates text that can be displayed in the window\&. "
.in -1c
.SH "Detailed Description"
.PP 
Utilities class for smaller and miscellaneous functions like the 'showFPS' one\&. 
.PP
Definition at line \fB43\fP of file \fBTTT\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "sf::Font TTT::Utils::createFont (std::string filename)\fC [static]\fP"

.PP
Function to create a font and load it\&. Shortens the amount of code that has to be written\&. 
.PP
\fBParameters\fP
.RS 4
\fIfilename\fP a string representing the path to the font file\&. 
.RE
.PP

.PP
Definition at line \fB81\fP of file \fBTTT_Utils\&.cpp\fP\&.
.SS "sf::Sprite TTT::Utils::createSprite (sf::Texture & texture, std::string filename)\fC [static]\fP"

.PP
Function to create and load a texture to a sprite\&. Shortens the amount of code that has to be written\&. Texture variable has to be created manually and passed as a paramter to the function because the sprites act weird when the texture is created in the function\&.
.PP
\fBParameters\fP
.RS 4
\fItexture\fP reference to the texture of type 'sf::Texture'\&. 
.br
\fIfilename\fP a string representing the path to the texture file\&. 
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBTTT_Utils\&.cpp\fP\&.
.SS "sf::Text TTT::Utils::createText (const sf::Font & font, unsigned int fontSize, sf::Vector2f position, std::string textContents)\fC [static]\fP"

.PP
Function creates text that can be displayed in the window\&. 
.PP
\fBParameters\fP
.RS 4
\fIfont\fP constant reference to the font of type 'sf::Font'\&. 
.br
\fIfontSize\fP unsigned integer representing the size of the font\&. 
.br
\fIposition\fP 2D vector representing the position on the x and y axis in the window\&. 
.br
\fItextContents\fP a string representing what text will be displayed in the window\&. 
.RE
.PP

.PP
Definition at line \fB138\fP of file \fBTTT_Utils\&.cpp\fP\&.
.SS "void TTT::Utils::showFPS (sf::RenderWindow & window, const sf::Font & font, unsigned int fontSize, sf::Color color = \fCsf::Color::White\fP)\fC [static]\fP"

.PP
'showFPS' calculates and displays a nice FPS number when the 'F3' key is pressed\&. 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP reference to the window of type 'sf::RenderWindow'\&. 
.br
\fIfont\fP constant reference to the font of type 'sf::Font'\&. 
.br
\fIfontSize\fP unsigned integer representing the size of the font\&. 
.br
\fIcolor\fP sf::Color representing the color of the FPS font with a default value of 'sf::Color::White'\&. 
.RE
.PP

.PP
Definition at line \fB33\fP of file \fBTTT_Utils\&.cpp\fP\&.
.SS "void TTT::Utils::sleepFor (int timeInSeconds)\fC [static]\fP"

.PP
Function makes the program 'sleep' for a specified amount of time in seconds\&. 
.PP
\fBParameters\fP
.RS 4
\fItimeInSeconds\fP integer representing the time in seconds\&. 
.RE
.PP

.PP
Definition at line \fB123\fP of file \fBTTT_Utils\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
