.TH "src/TTT_Utils.cpp" 3 "Mon Mar 6 2023" "Version v1.0.0" "TTT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TTT_Utils.cpp \- Defines the 'Utils' class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'include/TTT/TTT\&.hpp'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTTT\fP"
.br
.RI "The TTT namespace, which includes everything in the library\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "sf::Clock \fBTTT::clock\fP"
.br
.ti -1c
.RI "sf::Text \fBTTT::fpsText\fP"
.br
.ti -1c
.RI "std::stringstream \fBTTT::ss\fP"
.br
.ti -1c
.RI "bool \fBTTT::isKeyPressed\fP = false"
.br
.ti -1c
.RI "int \fBTTT::frameCount\fP = 0"
.br
.ti -1c
.RI "const float \fBTTT::startTime\fP = clock\&.getElapsedTime()\&.asSeconds()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the 'Utils' class\&. 


.PP
Definition in file \fBTTT_Utils\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for TTT from the source code\&.
